[colors.bright]
black = "#72696a"
blue = "#f38d70"
cyan = "#85dacc"
green = "#adda78"
magenta = "#a8a9eb"
red = "#fd6883"
white = "#fff1f3"
yellow = "#f9cc6c"

[colors.normal]
black = "#2c2525"
blue = "#f38d70"
cyan = "#85dacc"
green = "#adda78"
magenta = "#a8a9eb"
red = "#fd6883"
white = "#fff1f3"
yellow = "#f9cc6c"

[colors.primary]
background = "#2D2A2E"
foreground = "#fff1f3"

[cursor.style]
blinking = "Never"
shape = "Block"

[cursor.vi_mode_style]
blinking = "Never"
shape = "Block"

[env]
XDG_CONFIG_HOME = "$HOME/dotfiles/config"
XDG_DATA_HOME = "$HOME/dotfiles/share"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal]
osc52 = "CopyPaste"

[window]
# decorations = "Buttonless"
opacity = 0.8
