---
env:
  XDG_CONFIG_HOME: $HOME/dotfiles/config
  XDG_DATA_HOME: $HOME/dotfiles/share

window:
  opacity: 0.8
  decorations: "Buttonless"

font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: "Regular"
  bold:
    family: "JetBrainsMono Nerd Font"
    style: "Bold"

  italic:
    family: "JetBrainsMono Nerd Font"
    style: "Italic"

  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: "Bold Italic"
  size: 14

cursor:
  style:
    shape: "Block"
    blinking: "Never"
  vi_mode_style:
    shapre: "Block"
    blinking: "Never"

terminal:
  osc52: "CopyPaste"

colors:
  primary:
    background: '#2D2A2E'
    foreground: '#fff1f3'
  normal:
    black: '#2c2525'
    red: '#fd6883'
    green: '#adda78'
    yellow: '#f9cc6c'
    blue: '#f38d70'
    magenta: '#a8a9eb'
    cyan: '#85dacc'
    white: '#fff1f3'
  bright:
    black: '#72696a'
    red: '#fd6883'
    green: '#adda78'
    yellow: '#f9cc6c'
    blue: '#f38d70'
    magenta: '#a8a9eb'
    cyan: '#85dacc'
    white: '#fff1f3'
