DOTFILES="$HOME/dotfiles"

export XDG_CONFIG_HOME="$DOTFILES/config"
export XDG_CACHE_HOME="$DOTFILES/cache"
export XDG_DATA_HOME="$DOTFILES/share"
export XDG_STATE_HOME="$DOTFILES/state"

export ZSH="$XDG_CONFIG_HOME/oh-my-zsh"
export ZSHRC_PATH="$XDG_CONFIG_HOME/zsh"

export EDITOR="nvim"
export VISUAL="nvim"
alias v="nvim"

export HISTFILE="$ZSHRC_PATH/zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

plugins=(git gh gradle archlinux rust)

source "$ZSH/oh-my-zsh.sh"
source "$ZSHRC_PATH/themes/ohmyzsh-theme-passion/passion.zsh-theme"

alias rm="trash"
alias cat="bat --theme='Catppuccin Latte'"

for script in "$XDG_DATA_HOME/bash-scripts"/*; do
  alias ${script:t:r}="sh ${script}"
done

set -o vi

GPG_TTY=$(tty)
export GPG_TTY

source "$ZSHRC_PATH/plugins/yazi.zsh"
